version: "3.1"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: D1ymf8wyQEGthFR1E9xhCq
      POSTGRES_USER: LTIdbUser
      POSTGRES_DB: LTIdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://LTIdbUser:D1ymf8wyQEGthFR1E9xhCq@db:5432/LTIdb
      FRONTEND_URL: http://localhost:3000
      FILE_STORAGE_PATH: /app/storage
      NODE_ENV: development
    volumes:
      - ./storage-data:/app/storage
    ports:
      - "3010:3010"

volumes:
  postgres-data:
